config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  get "home/about"
  root "home#index"
  resources :pokemons, only: [ :index, :show ]
  get "search", to: "pokemons#search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pokemons = Pokemon.order(:number).page(params[:page]).per(12)
  end
  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Pokedex', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <%= form_with url: search_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.text_field :query, class: "form-control mr-sm-2", placeholder: "Search", "aria-label": "Search" %>
      <%= button_tag type: 'submit', 
          class: "btn btn-sm", 
          style: "background-color: #ff534f; width: 38px; height: 38px; padding: 6px; border-radius: 10px;",
          onmouseover: "this.style.backgroundColor='#cc4340'",
          onmouseout: "this.style.backgroundColor='#ff534f'" do %>
        <%= image_tag "whitepokeball-nobg.png", height: 20, alt: "Search" %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/home/_search.html.erb
<div class="p-4 rounded-4" style="background-color: white;">
  <%= form_with url: search_path, method: :get, class: "d-flex justify-content-center w-100" do |f| %>
      <%= f.text_field :query, 
          class: "form-control form-control-lg me-2", 
          style: "width: 80%; max-width: 800px; padding: 15px; font-size: 1.2rem; border-radius: 25px; background-color: transparent;",
          placeholder: "Search your Pokémon!", 
          "aria-label": "Search" %>
      <%= button_tag type: 'submit', 
          class: "btn btn-lg", 
          style: "background-color: #E8E8E8;",
          onmouseover: "this.style.backgroundColor='#D8D8D8'",
          onmouseout: "this.style.backgroundColor='#E8E8E8'" do %>
        <%= image_tag "whitepokeball-nobg.png", height: 30, alt: "Search" %>
      <% end %>
  <% end %>
</div>

app/views/home/about.html.erb
<h1> About us </h1>

app/views/home/index.html.erb
<div class="container py-2">

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
    <% @pokemons.each do |pokemon| %>
      <div class="col mb-4">
        <%= link_to pokemon_path(pokemon), class: "text-decoration-none" do %>
          <div class="card h-100 shadow" style="border: none; border-radius: 1rem;">
            <div class="card-body text-center">
              <div class="d-flex justify-content-center mb-3">
                <div class="d-flex align-items-center justify-content-center" style="width: 96px; height: 96px;">
                  <img src=<%= pokemon.image_url %> alt="<%= pokemon.name %>" style="width: 250px; height: auto;">
                </div>
              </div>
              
              <p class="text-muted mb-1">N°<%= pokemon.number %></p>
              <h5 class="card-title fw-bold mb-3" style="color: black;"><%= pokemon.name %></h5>
              
              <div class="d-flex justify-content-center gap-2">
                <% pokemon.types.each do |type| %>
                  <span class="badge rounded-pill px-3 py-2 mx-1" style="background-color: <%= type.color_code %>; color: black;"><%= type.name.upcase %></span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <!-- Pagination links at the bottom -->
  <div class="d-flex justify-content-center mt-4">
    <nav class="pokemon-pagination">
      <%= paginate @pokemons %>
    </nav>
  </div>
</div>